config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'products/favourites'
  resources :products, except: [:new, :edit, :update]
    get 'products/:id/edit', to: 'products#edit', as: 'edit_product'
  patch 'products/:id', to: 'products#update', as: 'update_product'
  patch 'products/:id/favourite', to: 'products#set_favourite', as:'favourite_product'

  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @product = Product.new
        @products = Product.order(:id)
    end

    def create
        @product = Product.new(product_params)
        @product.save
        redirect_to @product
    end

    def show
        @product = Product.find(params[:id])
    end 

    def edit
        @product = Product.find(params[:id])
    end

    def update
        product = Product.find(params[:id])
        product.update(product_params)
        redirect_to root_path
    end

    def set_favourite
        product = Product.find(params[:id])
        product.favourite = true
        product.save
        redirect_to product
    end
    
    def favourites
        @products = Product.where(favourite: true)
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to root_path, notice: 'Product has been removed'
    end 

    private

    def product_params
        params.require(:product).permit(:name, :price, :description, :image)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">Productos</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item ">
        <a class="nav-link" href="<%= asset_path root_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= asset_path products_favourites_path %>">Favourites</a>
      </li>
    
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RepasoPrueba</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">

      <%= render 'layouts/nav' %>
      <br>
      <br>
      <br>
      
      <%= yield %>

    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true, class: 'form-inline') do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.text_field :image, class: 'form-control' %>
  </div>

  <%= form.submit 'Enviar' %>

  <% end %>

app/views/products/edit.html.erb
<h1>SOY EL EDIT PERO NO ME VEO</h1>

<%= render 'products/form' %>



<%= link_to 'Back', root_path %>

app/views/products/favourites.html.erb
<h1>SOY LOS FAVORITOS</h1>

<table class="table">

  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Image</th>
    </tr>
  </thead>

  <tbody>
  <% @products.each do |producto| %>
    <tr>
    <td><%= producto.name %></td>
    <td><%= producto.price %></td>
    <td><%= producto.description %></td>
    <td><%= image_tag(producto.image, size: '40') %></td>
    </tr>
    
  <% end %>
    
  </tbody>

</table>

app/views/products/index.html.erb
<br>
<h1>SOY EL INDEX</h1>

<%= render 'products/form' %>



<br>
<table class="table">

  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Image</th>
    </tr>
  </thead>

  <tbody>
  <% @products.each do |producto| %>
    <tr>
    <td><%= producto.name %></td>
    <td><%= producto.price %></td>
    <td><%= producto.description %></td>
    <td><%= image_tag(producto.image, size: '40') %></td>
    <td><%= link_to 'Favourite', favourite_product_path(producto), method: :patch %></td>
    <td><%= link_to 'Edit', edit_product_path(producto) %></td>
    <td><button type="button" class="btn btn-danger"><%= link_to 'Delete?', product_path(producto), method: :delete %></button></td>
    </tr>
    
  <% end %>
    
  </tbody>

</table>

app/views/products/show.html.erb
<h1>OE OE SOY EL SHOEW!</h1>

Name:<%= @product.name %> <br>
Price:<%= @product.price %> <br>
Description:<%= @product.description %> <br>
It's favourite? <%= @product.favourite %> <br>
<%= link_to 'Back', root_path %>

<br>
<%= image_tag(@product.image, size: '500') %>